// 拼箱标识
export const lclFlagList = [{
  codeField: '',
  nameField: '全部'
}, {
  codeField: '0',
  nameField: '整箱'
}, {
  codeField: '1',
  nameField: '拼箱'
}]

export const taskTypeList = [{
  codeField: '',
  nameField: '全部'
}, {
  codeField: '0',
  nameField: '上传'
}, {
  codeField: '1',
  nameField: '委托'
}]
// 委托状态
export const entrustStatusTypeList = [{
  codeField: '',
  nameField: '全部'
}, {
  codeField: '0',
  nameField: '等待委托'
}, {
  codeField: '1',
  nameField: '等待处理'
}, {
  codeField: '2',
  nameField: '委托成功'
}, {
  codeField: '3',
  nameField: '委托退回'
}, {
  codeField: '4',
  nameField: '委托撤回'
}, {
  codeField: '5',
  nameField: '委托冻结'
}]
export const decStatus = [{
  codeField: '',
  nameField: '全部'
}, {
  codeField: '0',
  nameField: '接单生成'
}, {
  codeField: '2',
  nameField: '报关单预录入'
}, {
  codeField: '3',
  nameField: '待审核'
}, {
  codeField: '4',
  nameField: '审核驳回'
}, {
  codeField: '6',
  nameField: '审核通过'
}, {
  codeField: 'R',
  nameField: '待复核'
}, {
  codeField: '1',
  nameField: '单一窗口暂存'
}, {
  codeField: '2',
  nameField: '已申报'
}, {
  codeField: '3',
  nameField: '预录入接收失败'
}, {
  codeField: '4',
  nameField: '海关入库成功'
}, {
  codeField: '5',
  nameField: '海关入库失败'
}, {
  codeField: '6',
  nameField: '退单'
}, {
  codeField: '7',
  nameField: '审结'
}, {
  codeField: '8',
  nameField: '删单'
}, {
  codeField: '9',
  nameField: '放行'
}, {
  codeField: '10',
  nameField: '结关'
}, {
  codeField: '11',
  nameField: '查验通知'
}, {
  codeField: '000',
  nameField: '删单|改单|退单'
}]
